In [ ]:
import cv2
import numpy as np
 
 
img = cv2.imread('images/1.png')
gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

sift = cv2.xfeatures2d.SIFT_create()
kp, des = sift.detectAndCompute(gray, None)
# sift = cv2.xfeatures2d.SIFT_create()
 
 
# kp = sift.detect(gray,None)#找到关键点
print(kp)
img=cv2.drawKeypoints(gray,kp,img)#绘制关键点
 
cv2.imshow('sp',img)
cv2.waitKey(0)

In [6]:
kp, des = sift.compute(gray, kp)
print(len(kp))

952


In [9]:
print(des)

[[  3.   0.   0. ...  13.  22.   0.]
 [ 10.  13.   2. ...   0.  51. 142.]
 [  3.   7.   0. ...   0.   0.   0.]
 ...
 [134.  19.   0. ...   0.   3.  16.]
 [ 18.  34.   8. ...   0.   0.   0.]
 [  1.  64.  72. ...   0.   0.   2.]]
